# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "commonmark"
version = "0.1.8"
description = "CommonMark implementation for Gleam, for the BEAM or JS"
licenses = ["MIT"]
links = [
	{ title = "Demo", href = "https://mscharley.github.io/gleam-commonmark/" },
	{ title = "Sponsor", href = "https://github.com/sponsors/mscharley" },
]

[javascript]
#typescript_declarations = true

[repository]
type = "github"
user = "mscharley"
repo = "gleam-commonmark"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.6 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
glychee = ">= 1.1.2 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
startest = ">= 0.4.0 and < 1.0.0"
